/**
 * @file hitags_writer_i.h
 * @brief HiTagS Writer — internal header
 */

#pragma once

#include <furi.h>
#include <furi_hal.h>

#include <gui/gui.h>
#include <gui/view.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <notification/notification_messages.h>

#include <gui/modules/submenu.h>
#include <gui/modules/dialog_ex.h>
#include <gui/modules/popup.h>
#include <gui/modules/byte_input.h>
#include <gui/modules/widget.h>
#include <gui/modules/loading.h>

#include <dialogs/dialogs.h>
#include <storage/storage.h>
#include <toolbox/path.h>
#include <flipper_format/flipper_format.h>

#include <lfrfid/lfrfid_dict_file.h>
#include <lfrfid/protocols/lfrfid_protocols.h>

#include "scenes/hitags_writer_scene.h"
#include "hitag_s_proto.h"
#include "em4100_encode.h"

/* generated by fbt from .png files in images folder */
#include <hitags_writer_icons.h>

#define HITAGS_WRITER_TEXT_STORE_SIZE 64
#define HITAGS_WRITER_APP_FOLDER     EXT_PATH("lfrfid")
#define HITAGS_WRITER_APP_EXTENSION  ".rfid"

/* EM4100 ID is 5 bytes */
#define EM4100_ID_SIZE 5

/* Worker thread stack size */
#define HITAGS_WRITER_WORKER_STACK_SIZE (2 * 1024)

/* Worker stop flag — checked by continuous scan loop */
#define HITAGS_WORKER_FLAG_STOP (1UL << 0)

/* --- Custom Events --- */
typedef enum {
    HitagSEventNext = 100,
    HitagSEventExit,
    HitagSEventPopupClosed,
    HitagSEventWriteOk,
    HitagSEventWriteFailed,
    HitagSEventWriteRetrying,
    HitagSEventReadOk,
    HitagSEventReadFailed,
} HitagSCustomEvent;

/* --- Views --- */
typedef enum {
    HitagSViewSubmenu,
    HitagSViewDialogEx,
    HitagSViewPopup,
    HitagSViewWidget,
    HitagSViewByteInput,
    HitagSViewLoading,
} HitagSView;

/* --- Worker operation type --- */
typedef enum {
    HitagSWorkerIdle,
    HitagSWorkerWrite,
    HitagSWorkerReadUid,
    HitagSWorkerReadPages,
} HitagSWorkerOp;

/* --- Main App Structure --- */
typedef struct HitagSApp HitagSApp;

struct HitagSApp {
    /* Core framework */
    ViewDispatcher* view_dispatcher;
    SceneManager* scene_manager;
    Gui* gui;
    NotificationApp* notifications;

    /* Services */
    Storage* storage;
    DialogsApp* dialogs;

    /* GUI views */
    Submenu* submenu;
    DialogEx* dialog_ex;
    Popup* popup;
    Widget* widget;
    ByteInput* byte_input;
    Loading* loading;

    /* Worker thread */
    FuriThread* worker_thread;
    HitagSWorkerOp worker_op;
    bool worker_running;

    /* Working data */
    uint8_t em4100_id[EM4100_ID_SIZE]; /**< Target EM4100 ID to write */
    uint8_t read_id[EM4100_ID_SIZE];   /**< Last read EM4100 ID from tag */
    uint32_t read_pages[3];            /**< Last read page data [config, data_hi, data_lo] */
    uint32_t tag_uid;                  /**< Last read tag UID */
    uint32_t password;                 /**< Authentication password */
    HitagSResult last_result;          /**< Last operation result */

    /* Text buffers */
    char text_store[HITAGS_WRITER_TEXT_STORE_SIZE + 1];
    FuriString* file_path;

    /* LFRFID for file loading */
    ProtocolDict* dict;
    ProtocolId protocol_id;
};

/* --- Utility Functions --- */

void hitags_writer_popup_timeout_callback(void* context);
void hitags_writer_widget_callback(GuiButtonType result, InputType type, void* context);

/** Start worker thread for a given operation */
void hitags_writer_worker_start(HitagSApp* app, HitagSWorkerOp op);

/** Stop worker thread (blocks until done) */
void hitags_writer_worker_stop(HitagSApp* app);
